[tool.ruff]
# Set the maximum line length to 100
line-length = 100

# Assume Python 3.8
target-version = "py38"

# Include all Python files
include = ["*.py", "*.pyi", "**/pyproject.toml"]

[tool.ruff.lint]
# Enable specific rule sets
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
    "PL",   # pylint
    "RUF",  # ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E501",   # Line too long (handled by line-length)
    "PLR0913", # Too many arguments
    "PLR2004", # Magic value used in comparison
]

# Allow autofix for all enabled rules
fixable = ["ALL"]

# Don't autofix these
unfixable = []

# Exclude directories
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    ".streamlit",
]

[tool.ruff.lint.per-file-ignores]
# Ignore certain rules in test files
"test_*.py" = ["PLR2004", "S101"]

[tool.ruff.lint.isort]
# Configure import sorting
known-first-party = ["main", "app", "firearm_values", "price_analysis"]

[tool.ruff.lint.pydocstyle]
# Use Google-style docstrings
convention = "google"

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with 4 spaces
indent-style = "space"

# Respect magic trailing commas
skip-magic-trailing-comma = false

# Unix-style line endings
line-ending = "auto"