name: Auto-fix with Ruff

on:
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Run ruff fix
      run: |
        # Fix all auto-fixable issues
        ruff check . --fix
        
        # Format all files
        ruff format .
    
    - name: Check for changes
      id: check-changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Auto-fix: Apply ruff fixes and formatting"
        git push